### ISSUE TITLE
Unable to record/render

### ISSUE THREAD

**Issue by efosong** [DavidRother/cooking_zoo#21]
Hi. Firstly, thanks for working on this project!

It seems like rendering via setting `record=True` or via `.render()` is broken for `CookingEnvironment`. Looks like this is because a section of code was removed during a refactor: https://github.com/DavidRother/gym-cooking/blob/26d15aa677a159261e6fb0db98a73336b1289abf/gym_cooking/environment/cooking_zoo.py#L117-L125 

Is this a bug, or is rendering meant to be accessed some other way? 

Thanks

**Comment by DavidRother** [comment]
Hi, I will work on re-enabling this part. During the initial work this had to be disabled because of compatibility issues.

**Comment by DavidRother** [comment]
For documentation: rendering the environment does work now with the render function
